class AppStrings {
  static const Map<String, Map<String, String>> strings = {
    'en': {
      'app_name': 'Doctor Mitra',
      'tagline': 'Bihar\'s Own Doctor Platform',
      'find_doctor': 'Find Doctor',
      'book_appointment': 'Book Appointment',
      'search_hint': 'Search doctor or specialty...',
      'top_doctors': 'Top Rated Doctors',
      'see_all': 'See All',
      'specialties': 'Choose Specialty',
      'how_it_works': 'How It Works',
      'step1': 'Search Doctor',
      'step2': 'Book Slot',
      'step3': 'Get Receipt',
      'ambulance': 'Ambulance',
      'hospitals': 'Hospitals',
      'health_card': 'Health Card',
      'online_consult': 'Online Consult',
      'login': 'Login',
      'logout': 'Logout',
      'my_bookings': 'My Bookings',
      'profile': 'Profile',
      'home': 'Home',
      'doctors': 'Doctors',
      'verified': 'Verified',
      'book_now': 'Book Now',
      'view_profile': 'View Profile',
      'experience': 'Experience',
      'fee': 'Fee',
      'rating': 'Rating',
      'available_today': 'Available Today',
      'online': 'Online',
      'morning_slots': 'Morning Slots',
      'evening_slots': 'Evening Slots',
      'select_slot': 'Select Time Slot',
      'confirm_booking': 'Confirm Booking',
      'booking_confirmed': 'Booking Confirmed!',
      'patient_name': 'Patient Name',
      'phone_number': 'Phone Number',
      'age': 'Age',
      'symptoms': 'Symptoms / Problem',
      'optional_symptoms': 'Symptoms / Problem (optional)',
      'required_field': 'This field is required',
      'invalid_phone': 'Enter a valid 10-digit phone number',
      'booking_id': 'Booking ID',
      'appointment_details': 'Appointment Details',
      'booking_saved': 'Your appointment has been saved',
      'total_fee': 'Total Fee',
      'platform_fee': 'Platform Fee',
      'free': 'FREE',
      'share_whatsapp': 'Share on WhatsApp',
      'go_home': 'Go to Home',
      'emergency_call': 'EMERGENCY CALL 102',
      'call_now': 'Call Now',
      'blood_group': 'Blood Group',
      'emergency_contact': 'Emergency Contact',
      'allergies': 'Known Allergies',
      'medications': 'Current Medications',
      'generate_card': 'Generate Health Card',
      'download_card': 'Download Card',
      'otp_login': 'OTP Login',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'enter_phone': 'Enter Phone Number',
      'enter_otp': 'Enter 6-digit OTP',
      'upcoming': 'Upcoming',
      'past': 'Past',
      'cancelled': 'Cancelled',
      'no_bookings': 'No bookings found',
      'cancel': 'Cancel',
      'data_safe': 'Your data is safe. We never share it.',
      'teleconsult': 'Video Consultation',
      'device_diagnostics': 'Pre-Call Diagnostics',
    },
    'hi': {
      'app_name': 'डॉक्टर मित्र',
      'tagline': 'बिहार का अपना डॉक्टर प्लेटफॉर्म',
      'find_doctor': 'डॉक्टर खोजें',
      'book_appointment': 'अपॉइंटमेंट बुक करें',
      'search_hint': 'डॉक्टर या विशेषता खोजें...',
      'top_doctors': 'शीर्ष डॉक्टर',
      'see_all': 'सभी देखें',
      'specialties': 'विशेषता चुनें',
      'how_it_works': 'कैसे काम करता है',
      'step1': 'डॉक्टर खोजें',
      'step2': 'स्लॉट बुक करें',
      'step3': 'रसीद पाएं',
      'ambulance': 'एम्बुलेंस',
      'hospitals': 'अस्पताल',
      'health_card': 'स्वास्थ्य कार्ड',
      'online_consult': 'ऑनलाइन परामर्श',
      'login': 'लॉगिन',
      'logout': 'लॉगआउट',
      'my_bookings': 'मेरी बुकिंग',
      'profile': 'प्रोफ़ाइल',
      'home': 'होम',
      'doctors': 'डॉक्टर',
      'verified': 'सत्यापित',
      'book_now': 'अभी बुक करें',
      'view_profile': 'प्रोफ़ाइल देखें',
      'experience': 'अनुभव',
      'fee': 'शुल्क',
      'rating': 'रेटिंग',
      'available_today': 'आज उपलब्ध',
      'online': 'ऑनलाइन',
      'morning_slots': 'सुबह के स्लॉट',
      'evening_slots': 'शाम के स्लॉट',
      'select_slot': 'समय स्लॉट चुनें',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'booking_confirmed': 'बुकिंग की पुष्टि हो गई!',
      'patient_name': 'मरीज का नाम',
      'phone_number': 'फ़ोन नंबर',
      'age': 'उम्र',
      'symptoms': 'लक्षण / समस्या',
      'optional_symptoms': 'लक्षण / समस्या (वैकल्पिक)',
      'required_field': 'यह जानकारी जरूरी है',
      'invalid_phone': 'मान्य 10 अंकों का फ़ोन नंबर डालें',
      'booking_id': 'बुकिंग आईडी',
      'appointment_details': 'अपॉइंटमेंट विवरण',
      'booking_saved': 'आपका अपॉइंटमेंट सेव हो गया है',
      'total_fee': 'कुल शुल्क',
      'platform_fee': 'प्लेटफॉर्म शुल्क',
      'free': 'मुफ़्त',
      'share_whatsapp': 'व्हाट्सएप पर शेयर करें',
      'go_home': 'होम पर जाएं',
      'emergency_call': 'आपातकालीन कॉल 102',
      'call_now': 'अभी कॉल करें',
      'blood_group': 'रक्त समूह',
      'emergency_contact': 'आपातकालीन संपर्क',
      'allergies': 'ज्ञात एलर्जी',
      'medications': 'वर्तमान दवाइयां',
      'generate_card': 'स्वास्थ्य कार्ड बनाएं',
      'download_card': 'कार्ड डाउनलोड करें',
      'otp_login': 'ओटीपी लॉगिन',
      'send_otp': 'ओटीपी भेजें',
      'verify_otp': 'ओटीपी सत्यापित करें',
      'enter_phone': 'फ़ोन नंबर दर्ज करें',
      'enter_otp': '6 अंकों का ओटीपी दर्ज करें',
      'upcoming': 'आगामी',
      'past': 'पिछली',
      'cancelled': 'रद्द',
      'no_bookings': 'कोई बुकिंग नहीं मिली',
      'cancel': 'रद्द करें',
      'data_safe': 'आपका डेटा सुरक्षित है। हम इसे कभी साझा नहीं करते।',
      'teleconsult': 'वीडियो परामर्श',
      'device_diagnostics': 'प्री-कॉल डायग्नोस्टिक्स',
    }
  };
}
